# Generated by Django 5.1.2 on 2024-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='matric_number',
            field=models.CharField(default='2655', max_length=100),
        ),
    ]
